version: '3.2'
services:
  mynodejs:
    hostname: mynodejs
    container_name: my-nodejs
    build:
      context: .
      dockerfile: docker/nodejs.dockerfile
    volumes:
      - ./:/var/app
    networks:
      - default
  myapache:
    hostname: myapache
    container_name: my-apache
    build:
      context: .
      dockerfile: docker/apache.dockerfile
    ports:
      - '7777:80'
    volumes:
      - ./docker/apache/extra:/usr/local/apache2/conf/extra
    networks:
      - default
  mynginx:
    image: bitnami/openresty:latest
    hostname: mynginx
    container_name: my-nginx
    # build:
    #   context: .
    #   dockerfile: docker/nginx.dockerfile
    working_dir: /var/www/html
    ports:
      - "8888:80"
      - "4444:443"
    volumes:
      - ./docker/nginx/ssl:/etc/ssl:ro
      - ./docker/nginx/sites-dev/jurassicjs.eu.conf:/opt/bitnami/openresty/nginx/conf/server_blocks//jurassicjs.eu.conf:ro
    networks:
      - default
