version: '3.2'
services:
  mynodejs:
    hostname: mynodejs
    container_name: mynodejs
    build:
      context: .
      dockerfile: docker/nodejs.dockerfile
    volumes:
      - ./:/var/app
    networks:
      - default
  myapache:
    hostname: myapache
    container_name: myapache
    build:
      context: .
      dockerfile: docker/apache.dockerfile
    ports:
      - '7777:80'
    volumes:
      - ./docker/apache/extra:/usr/local/apache2/conf/extra
    networks:
      - default
